apiVersion: apps/v1
kind: Deployment
metadata:
  name: ieee-deployment
  labels:
    app: ieee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ieee
  template:
    metadata:
      labels:
        app: ieee
    spec:
      containers:
      - name: ieee
        image: hasanalperen/itu-ieee-ras:imageversion
        ports:
        - containerPort: 5000
